server:
  port: 7777

# 1-3 在yml文件配置服务器验证地址
# 是否开启cas单点登录功能, true则cas配置项生效, 使用cas进行登录, false则使用本地登录页面登录
login:
  cas: true
  # 多个url用"|"分割
  cas-ignore-host-url:
    http://localhost/api/user/verify
  cas-web-home-page-url:
    http://localhost/#/live

# cas配置项, 只在login.cas为true时生效
cas:
  server-url-prefix: http://localhost:10086/cas
  server-login-url: http://localhost:10086/cas/login
  client-host-url: http://localhost:${server.port}
  validation-type: CAS3